### ISSUE TITLE
[Bug] 배경으로 이미지를 넣었을 때 썸네일이 다운로드 되지 않는 현상

### ISSUE THREAD

**Issue by LAH1203** [usageness/thumbnail-Generator#4]
## 발생 상황

![썸네일생성기-버그](https://user-images.githubusercontent.com/57928612/204517763-e04df0a1-c8a4-4b24-8bec-7266554e653b.gif)

배경으로 이미지를 넣은 후 다운로드 버튼 클릭 시 썸네일이 다운로드 되지 않고 페이지가 재시작되는 현상 발생

**Comment by usageness** [comment]
서버에서 허용하지 않은 경로로 외부 이미지를 불러올때 생기는 CORS 정책 문제로 확인되었습니다.
별도의 프록시 서버를 구축하여 우회할 수 있도록 업데이트 하겠습니다.
버그 제보 감사합니다 😊

**Comment by usageness** [comment]
문제가 해결되어 이슈를 닫습니다.
- [chore: proxy 서버 주소 변경](https://github.com/usageness/thumbnail-Generator/commit/dd2d9f8a4d43433371ebc136b1679d4413ff89af)
